# site details
title: To Bleed At A Typewriter
tag_line: a writing blog
description: A writing blog.
keywords: poetry poems writing
url: https://writing.theconfused.me
author: Lingyi Hu
author_url: https://writing.theconfused.me/about/
email_subscribe: http://eepurl.com/cNZfVz

markdown: kramdown

permalink: /:title/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post

