baseURL = "https://writing.theconfused.me"
languageCode = "en-us"
title = "当时年少春衫薄"
theme = "curry"
metaDataFormat = "yaml"

[permalinks]
post = "/:slug/"

[params]
dateFormat = "2006年01月02日"
monthDateFormat = "01月02日"

[frontmatter]
date  = [":filename", ":default"]

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackFriday]
    extensions = ["hardLineBreak"]

[taxonomies]
category = "category"